name: pretty_notes
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: null
  google_fonts: ^6.2.1
  uuid: ^4.5.1

dev_dependencies:

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/flutter_logo.png
    - assets/
