// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ2i_2NohNbxTV4uW4nY7pQB1xATWfxs8',
    appId: '1:1097236270475:web:b24ee50fb45c81f5e2b38e',
    messagingSenderId: '1097236270475',
    projectId: 'pretty-notes-f6928',
    databaseURL:
        "https://pretty-notes-f6928-default-rtdb.asia-southeast1.firebasedatabase.app",
    authDomain: 'pretty-notes-f6928.firebaseapp.com',
    storageBucket: 'pretty-notes-f6928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf06b5R0fUGqjNkPoV_UgO9HUjHsl4l0Q',
    appId: '1:1097236270475:android:244ac3539447dfbbe2b38e',
    messagingSenderId: '1097236270475',
    projectId: 'pretty-notes-f6928',
    databaseURL:
        "https://pretty-notes-f6928-default-rtdb.asia-southeast1.firebasedatabase.app",
    storageBucket: 'pretty-notes-f6928.firebasestorage.app',
  );
}
